### ISSUE TITLE
Install from source on Apple Silicon Mac

### ISSUE THREAD

**Issue by TingjieGuo** [symengine/symengine.R#118]
Hi all,

I was trying to install symengine.R from source on a M1 Macbook. But I always got the error message "Could NOT find MPFR (missing: MPFR_LIBRARIES MPFR_INCLUDE_DIRS)". I checked my CPPFLAGS and LDFLAGS and they seem to point to the right directory where I do have mpfr (following the instruction from this repo readme). I can't figure out what was going wrong exactly. It seems related to this issue (https://github.com/symengine/symengine/issues/1576) but I don't if this is still the case since it was from a few years back. Does anyone have an idea how I can get it fixed? Many thanks in advance!

Best,
Tingjie

**Comment by Marlin-Na** [comment]
Hi @TingjieGuo,

Assuming your R is installed from official installer instead of HomeBrew, I would suggest downloading the GMP and MPFR binaries from https://mac.r-project.org/bin/. 

It seems that they have a script for that. Basically it will download the binaries and extract to `/opt/R/arm64` (arm64) or `/usr/local` (x86_64).
