### ISSUE TITLE
Do you know if the CRAN binaries will ship with symengine binaries?

### ISSUE THREAD

**Issue by mattfidler** [symengine/symengine.R#39]
Just a question -- I'm unsure if you know the answer.

**Comment by Marlin-Na** [comment]
My understanding is that CRAN will build package binaries for Windows and Mac OS, so that users can install directly with `install.packages`. However, CRAN does not provide binaries for Linux user so that they will need to build from source -- which may require user to compile symengine library themselves, e.g. via the script provided on README.

**Comment by mattfidler** [comment]
That is fine with me.  I was a bit worried about trying to provide install instructions for Mac OS users.
